version: "3.1"
services:
  music-library-database:
    build: ./database
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    image: nfmatten/music-library-database:1.0.0

  music-library-backend:
    build: ./backend
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - music-library-database
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata songs_fixture && python manage.py runserver 0.0.0.0:8000"
    image: nfmatten/music-library-backend:1.0.0

  music-library-frontend:
    build: ./frontend
    ports:
      - 3001:3000
    restart: always
    depends_on:
      - music-library-backend
    image: nfmatten/music-library-frontend:1.0.0
